# Generated by Django 6.0.5 on 2026-05-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
