# Generated by Django 6.0.5 on 2026-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_payment_doctor_remove_payment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
